### ISSUE TITLE
Set-up not working.

### ISSUE THREAD

**Issue by kylesloper** [dafiulh/eleventy-plugin-tailwindcss#20]
I've followed through the setup guide, and tailwind is still taking no effect. Here is a link to the repo if you want to have a quick check over. (I've invited you) https://github.com/moonfacedesign/moonface/tree/pre-alpha

**Comment by daflh** [comment]
[These lines](https://github.com/moonfacedesign/moonface/blob/pre-alpha/.eleventy.js#L64-L72) should be:
```js
eleventyConfig.addPlugin(pluginTailwindCSS, {
  src: "_includes/assets/css/mf-site.css",
  dest: "_includes/assets/css",
  keepFolderStructure: false,
  minify: true
  // See below for other available options
});
```

**Comment by kylesloper** [comment]
Hey man, unfortunately it's still not working. I've tried it out on an emptier repo and still no result even though I get this message which appears to be promising.
![image](https://user-images.githubusercontent.com/45979758/112754678-16e75f00-8fd5-11eb-970f-00d7a1d76de1.png)


Here's the repo https://github.com/moonfacedesign/eleventy-starter

**Comment by daflh** [comment]
Ah I see, it's not the problem with the plugin, but it's because you pass through copy the entire `_includes/assets/` folder, see [this line](https://github.com/moonfacedesign/eleventy-starter/blob/v1/.eleventy.js#L91). Because this plugin runs first before Eleventy does all those writes, it causes the file that has been written earlier by this plugin to be overwritten by Eleventy.

My suggestion is to change that one line to be more specific in which folder to copy, for example you can do it like this:
```js
eleventyConfig.addPassthroughCopy("_includes/assets/js/");
```

**Comment by kylesloper** [comment]
Thanks, I'll try this now. To be clear, what dependencies do I need for this plugin to run at the moment I just have `tailwindcss` ,`postcss-cli` and `autoprefixer`.

Thanks for you help.

**Comment by daflh** [comment]
You don't need to install anything actually, this plugin is already includes `tailwaindcss`, `autoprefixer` and `clean-css`, those will automatically installed when you install this package

**Comment by daflh** [comment]
Is this fixed? Or are there any other issues?

**Comment by kylesloper** [comment]
Unfortunately, It's still not working. I have followed the steps through and there is still no result. To be clear I am using Netlify dev do I need to set my npm scripts differently?

**Comment by daflh** [comment]
Can you specify which parts that not working? Or is it the same as above?

**Comment by kylesloper** [comment]
To be honest I'm not sure, the plugin seems to be running but there aren't any styling changes when I run either `netlify dev` or `npm run build` (with the npm script of:
```
    "build": "npx eleventy & netlify dev",
```

I've updated the repo.

**Comment by daflh** [comment]
The `build` script should be only `npx eleventy`, and it works fine on my machine.

![Screenshot 2021-03-30 010232](https://user-images.githubusercontent.com/30594815/112879873-eea25200-90f3-11eb-932d-7d993e948a85.png)

Umm, maybe you can tell me what you expected and what you got instead?

**Comment by kylesloper** [comment]
The navigation links should have a background of red as seen here:
```
<nav class="bg-red-900">
```

Yes, that's the thing the css is generated but doesn't have any effect on the site.

**Comment by kylesloper** [comment]
My apologies, seems like a stupid mistake I made. For some reason the css is not used when using the nunjucks `set css`:

*Before*
```
    {% include "assets/css/tw.css" %}
```
*After*
```
       <link href="/_includes/assets/css/tw.css" rel="stylesheet">
```

Works as expected now 👍

**Comment by daflh** [comment]
Ahh, I just wanted to comment on that. Great.

Are there any other issues?

**Comment by kylesloper** [comment]
No that's all. Thank you very much for your time.
