### ISSUE TITLE
Missing styles after Netlify deploy.

### ISSUE THREAD

**Issue by kylesloper** [dafiulh/eleventy-plugin-tailwindcss#22]
Styles look normal on `Netlify dev` (locally) however after deploy there is no styling. My build command is `npm run build`.. is this the correct config for this plugin?

![image](https://user-images.githubusercontent.com/45979758/114279831-78281d00-9a2e-11eb-8717-b334d9042243.png)

**Comment by daflh** [comment]
Is the CSS file exist? If not, maybe you added CSS file to `.gitignore`

**Comment by kylesloper** [comment]
I've downloaded the deploy from Netlify and it seems that the entire `css` directory is missing. Is there a common reason for this?

**Comment by daflh** [comment]
Can I see your `package.json` content?

**Comment by kylesloper** [comment]
{
  "name": "redacted",
  "title": "redacted",
  "version": "1.0.3",
  "description": "redacted",
  "scripts": {
    "build": "npx eleventy",
    "watch": "npx eleventy --watch",
    "debug": "DEBUG=* npx eleventy"
  },
  "repository": {
    "type": "git",
    "url": "redacted"
  },
  "author": {
    "name": "redacted",
    "email": "redacted",
    "url": "redacted"
  },
  "license": "MIT",
  "bugs": {
    "url": "redacted"
  },
  "devDependencies": {},
  "dependencies": {
    "@11ty/eleventy": "^0.11.1",
    "@11ty/eleventy-navigation": "^0.1.6",
    "clean-css": "^4.2.1",
    "eleventy-plugin-tailwindcss": "^0.3.0",
    "html-minifier": "^4.0.0",
    "luxon": "^1.26.0",
    "markdown-it": "^10.0.0",
    "markdown-it-anchor": "^5.3.0",
    "netlify-cli": "^3.16.2",
    "uglify-es": "^3.3.9"
  }
}

**Comment by daflh** [comment]
Hmmm, maybe do you have any public repository with the same issue that I can take a look at? Because I can't reproduce.

**Comment by kylesloper** [comment]
This is the repo with that issue, I've given you access.

https://github.com/moonfacedesign/moonface/

**Comment by daflh** [comment]
Wait, are you sure styles look normal on local env? The CSS messed up when I try to run `netlify dev`

**Comment by kylesloper** [comment]
Yeah styles are completely fine on local. I did reset the repo to before I was messing around trying to fix the issue shortly after I added you, is it possible you've cloned the old one?

**Comment by daflh** [comment]
But this https://i.ibb.co/nLLggVJ/1618142123061.png doesn't look fine, the correct branch is "v1" right?

**Comment by kylesloper** [comment]
Yeah that's the correct branch. That's strange styles are looking okay in my local build.

![image](https://user-images.githubusercontent.com/45979758/114303815-ebca3880-9ac7-11eb-96b2-681cd33e4de3.png)

**Comment by daflh** [comment]
Well, that's weird. Give me a screenshot of the _view-source_ please, maybe something's different.

**Comment by kylesloper** [comment]
View source should be the same as https://moonface.ga

Unless you want me to copy paste my local view-source, its not really a readable file.

**Comment by kylesloper** [comment]
Not too sure how to screenshot it, it's a very long file. Do you want me to copy paste instead?

**Comment by daflh** [comment]
I mean just the \<head\> part, but okay copy paste is fine, but don't paste here, use Pastebin then send the link here

**Comment by kylesloper** [comment]
https://pastebin.com/tUet4eAG

**Comment by daflh** [comment]
Do you disable Tailwind "jit" mode locally?

**Comment by kylesloper** [comment]
No I did not.

**Comment by kylesloper** [comment]
I have disabled that and pushed. Netlify deploy still showing no styles coming from `tw.css`

**Comment by daflh** [comment]
Send the Netlify deploy log here using Pastebin, I will take a look

**Comment by kylesloper** [comment]
https://pastebin.com/SdvBVvBt

**Comment by daflh** [comment]
I see, so Netlify is using Node v10.24.1, but there's a code using `flatMap` which is only available in Node > v11.0.0. Add `.nvmrc` to your repo with the contents of `v12` and it should work fine. [Read more](https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-and-javascript).

**Comment by kylesloper** [comment]
Unfortunately no fix yet, this time the `tw.css` file is processed but only contains this.
https://pastebin.com/D2s33krR

It's weird because it has partially generated my styles from `tw.css`

**Comment by daflh** [comment]
I see you're enabling back the "jit" mode in the latest commit, if you wanna do that, you need to set the `purge` property with the template files path.

**Comment by daflh** [comment]
For example:
```js
module.exports = {
  purge: [
    './**/*.njk'
  ],
  darkMode: false, // or 'media' or 'class'
  mode: 'jit',
...
```

See https://tailwindcss.com/docs/just-in-time-mode#enabling-jit-mode

**Comment by kylesloper** [comment]
Thank you so much for your time, it's working perfectly now. Great plugin btw ❤

**Comment by daflh** [comment]
Good to hear that.
Can I close this issue?

**Comment by kylesloper** [comment]
Of course :))
