### ISSUE TITLE
JIT causing some classes to just not work.

### ISSUE THREAD

**Issue by kylesloper** [dafiulh/eleventy-plugin-tailwindcss#28]
I'm going to file this issue in the event that this is a bug within this plugin and not Tailwind itself. I say this because there have been several recent reports that `JIT` is causing some issues.. so I will also create an issue on the Tailwind repo too.

A simple example of the issue:
```
<nav class="relative p-12">
  <img class="w-20 mx-auto" src="/static/logo.svg" alt="Logo">
  <h1 class="text-center">Simple navigation</h1>
</nav>
```

**With `JIT` on padding with value of `12` doesn't work at all.**

**With `JIT` off padding with value of `12` works like ususal**

## Go to [tailwind issue](https://github.com/tailwindlabs/tailwindcss/issues/4552) to see further instructions on reproducible example.

Let me know if you need anything else to investigate.

Thanks.

**Comment by JonKaric** [comment]
You have an error in your code, you've missed the end quote.

`<nav class="relative p-12>`

Should be
`<nav class="relative p-12">`

**Comment by kylesloper** [comment]
Sorry that appears to just be an error in the issue itself.. I'll fix that right away.

Look at the tailwind issue for a detailed reproducible example.

Thanks

**Comment by kylesloper** [comment]
Comment on issue from the guys over at Tailwind:

> Hey! When I start the project in JIT mode the padding is there:
> 
> <img alt="image" width="1625" src="https://user-images.githubusercontent.com/4323180/120830748-d227f900-c52c-11eb-926c-3fdb97fb1117.png">
> 
> But when I change the padding, the changes aren't picked up.
> 
> A few things I noticed:
> 
> 1. You are watching an enormous amount of files because your purge config is capturing all of `node_modules`. The JIT takes 17s to run because it is evaluating 22,957 files and finding 1,132,230 potential classes. Make sure you change your purge config so it doesn't include the entire `node_modules` directory.
> 2. You are putting your templates in hidden folders like `.components`, and glob patterns ignore hidden folders, so I suspect when we pass those globs to our watch process they are being ignored 🤔  I tried switching to regular folders though and it didn't fully resolve the issue.
> 3. I think the main issue is that the eleventy plugin is just not designed to work with the JIT engine. It is doing a lot of manual file watching and stuff rather than working like a traditional PostCSS plugin, which means (I suspect) that the dependency messages we send out to PostCSS aren't being respected, and the plugin is not triggering a CSS rebuild when your template files change.
> 
> I did verify after changing the purge config and changing the hidden folders to be regular folders that re-saving the _config_ file _did_ trigger a CSS rebuild and make everything look correct, and I noticed the plugin is explicitly watching the config file, so I think the change that needs to happen here is that the plugin needs to watch the purge paths as well. Because it is such an incredibly low-level integration doing a bunch of stuff manually that we normally expect to "just work" when we fire out a PostCSS dependency message, there's not really anything we can change on our end to improve this I'm afraid :/
> 
> I think your best option is to compile your CSS separately instead of relying on the integration, using postcss-cli or our new JIT-compatible CLI tool we will be releasing in a week or so if you can wait. Then just import the compiled CSS into your 11ty project, and run both the 11ty server and the PostCSS watch process simultaneously using `npm-run-all` or `concurrently`. Hope that helps.


I don't know how this plugin could evolve into a `JIT`-friendly system but based on the usability and seamlessness of it all.. I would love for it to feature these properties. Let me know if I can be of any help at all.
