### ISSUE TITLE
Allow option to rerun tailwind every time I save any file (not just the CSS file)

### ISSUE THREAD

**Issue by tarngerine** [dafiulh/eleventy-plugin-tailwindcss#4]
Hi there! Thank you for making this — I was really struggling as someone new to Webpack, PostCSS, tailwind, and eleventy on how to get Tailwind set up, and this plugin made it super duper easy!

One thing I'm running into — when I save any file Eleventy is watching (I use `serve` option) and the browser reloads, I noticed in console logs it's not actually re-running Tailwind. 

<img width="937" alt="image" src="https://user-images.githubusercontent.com/1629901/92980459-efc3a880-f45b-11ea-97c1-017c778f1e8e.png">

I assume this is because most people run Tailwind without purging in development mode.

However, my computer gets extremely slow if I run Tailwind without purging. Something about the giant CSS file is making Firefox chug. So I set `purge.enabled: true` in `tailwind.config.js`

```
purge: {
    enabled: true,
    content: [
      './src/**/*.njk',
      './src/**/*.md'
    ]
  },
```

With purge enabled, any time I reference a Tailwind class that's unused when I start the Eleventy serve, it doesn't work (because it was purged).

My request is: is there someway so that I can configure this plugin to watch not only the CSS files for change, but also anything that Eleventy watches, too?

---

Steps to repro:
- Have some element with a class, like mt-2
- Set purge.enabled: true
- Run Eleventy with --serve
- Change that mt-2 to a previously unused Tailwind class to an `.njk` (or other template file), e.g. mt-4

Expected
- That new class is available and renders correctly, e.g. mt-4

Actual
- That class (e.g. mt-4) is unavailable (as it was purged when serving started) and the element doesn't have any margin top.
- If you change back to mt-2 it works, as that wasn't purged.

---

Thank you so much!

**Comment by tarngerine** [comment]
Neveremind, I got it to work by removing my hyper-specific `src` definiton!

**Comment by tarngerine** [comment]
Wait nvm it's still not working, sorry!

**Comment by dafiulh** [comment]
Sorry to keep you waiting, I wasn't feeling well a few days ago, so I didn't have time to check Github
By the way, thanks for opening the issue, I will resolve this asap

**Comment by tarngerine** [comment]
Hope you feel better! No rush!

**Comment by daflh** [comment]
I've added new option for this
Just update this package to [v0.2.5](https://github.com/dafiulh/eleventy-plugin-tailwindcss/releases/tag/v.0.2.5), then add `watchEleventyWatchTargets` option, like this:
```js
const pluginTailwindCSS = require("eleventy-plugin-tailwindcss");
module.exports = function(eleventyConfig) {
    eleventyConfig.addPlugin(pluginTailwindCSS, {
        watchEleventyWatchTargets: true
    });
};
```
Feel free to open new issues if you have any suggestions, thanks!
